version: "3.1"

services:
  web-1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./www1:/var/www/html
    ports:
      - "81:80"

  web-2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./www2:/var/www/html
    ports:
      - "82:80"
