version: "3"
services:
  www:
    build: .
    container_name: webhost
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/
    links:
      - db
    networks:
      - default
      
  db:
    image: mysql
    restart: always
    container_name: DataBaseServer
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/var/lib/mysql

    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PHP_MySQL
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test


    
